### ISSUE TITLE
Highlight with mouseover 

### ISSUE THREAD

**Issue by arnaudspotfire** [hski-github/spotfire-sankey-diagram#12]
When mouseovering a flow or a categorie in axis, it would be nice if the flow could be highlighted with a border like we currently have in other Spotfire visualization.

![Screen Shot 2021-05-21 at 14 58 56](https://user-images.githubusercontent.com/15086293/119141043-199a8980-ba45-11eb-9c86-8b7abe7f7acc.png)

**Comment by hski-github** [comment]
The approach using Reusing shapes: Tranforms from https://css-tricks.com/how-to-add-a-double-border-to-svg-shapes/
looks interesting. 
Or simply add another rect or path with bigger dimension and hide it by default and show it on mouseover event.

**Comment by hski-github** [comment]
@arnaudtibco @mrylande Is there some support from the mods framework to trigger such event? Simple JavaScript onmouseover event would be too quick, because like for tooltip some delay and waiting over the object should happen before it get highlighted. Should be maybe kind of triggered by the tooltip? And as a minor topic, do you know how to get or what is the default color for the line for highlighting?

**Comment by arnaudspotfire** [comment]
Hello @hski-github ! I do not know. I will ask the team. 
I also belive these types questions relates to the Mods API and could be asked directly from the Mods GitHub repo (https://github.com/TIBCOSoftware/spotfire-mods).

**Comment by arnaudspotfire** [comment]
Hello ! It is controlled by the theme. Tested a bit and seems to be set by the font color defined in 'Visualization general’.

Best regards,
Arnaud

**Comment by hski-github** [comment]
https://stackoverflow.com/questions/21949343/show-a-div-only-when-user-hover-an-element-for-couple-seconds

https://css-tricks.com/almanac/properties/t/transition-delay/

**Comment by hski-github** [comment]
@arnaudtibco I have added outline on mouseover in pull request #23 resp. branch 'outline'. Would be great if you could have a look and test it.

**Comment by arnaudspotfire** [comment]
Hello ! I just tested it and I think it looks good. The outline looks perfect on non-rectangular bars but a bit blurry on rectangular bars. But I think this is acceptable from a UX perspective.

![Screen Shot 2021-10-21 at 09 24 15](https://user-images.githubusercontent.com/15086293/138230780-e260cfdf-f205-44ae-acc9-91ca47611a10.png)
![Screen Shot 2021-10-21 at 09 24 27](https://user-images.githubusercontent.com/15086293/138230792-5a636701-5703-437f-8162-178f218eb27d.png)

**Comment by hski-github** [comment]
Thank you for testing! 😊 I am taking font.color from the Mods API styling information and use 1 px stroke width and 1 px padding for the outline. This is just guessing. Could be useful to have more layout guidance from TIBCO about such things. And more detailed styling information in the Mods API.
