### ISSUE TITLE
Marking categories or connections

### ISSUE THREAD

**Issue by arnaudspotfire** [hski-github/spotfire-sankey-diagram#14]
Marking categories or connections should be possible directly from the Sankey.

**Comment by hski-github** [comment]
Hm, from the short description I would say, this should work already. 

what browser are you using?

**Comment by arnaudspotfire** [comment]
I'm using Chrome (90.0.4430.212). Just tried again and there is no effect when I click on category or a connection.

**Comment by hski-github** [comment]
Hm, strange. Works on my side with Chrome on MacOS. 

https://user-images.githubusercontent.com/1921015/119151234-7b5ff100-ba4f-11eb-8fdc-8385ecaffc07.mov

**Comment by arnaudspotfire** [comment]
Yes this works. 
What I meant is being able to mark not only flow(s) but also being able to mark the categories or connection (the grey axis). For instance, in your example, being able to mark the categorie A from the After axis by click the A vertical grey line, to all the flows linked to it.

**Comment by hski-github** [comment]
In the last second of the screen recording I am clicking on the grey bar of A of Today. Is that what you mean?

I added this feature very recently. Maybe you need to sync your repo to use most recent version of main.

**Comment by arnaudspotfire** [comment]
Yes this exactly what I meant. I will check shortly.

**Comment by arnaudspotfire** [comment]
Hello Holger,
I checked today and it works perfectly!
