### ISSUE TITLE
Show bar segments with 0 incoming/outgoing items

### ISSUE THREAD

**Issue by hski-github** [hski-github/spotfire-sankey-diagram#15]
Basically I want to show transactions from 8 possible states (i.e. 8 possible starting points on the left, same 8 possible arrival points on the right). Starting and arriving bars are correctly sized based on the outcoming/incoming transactions. Since I am using current filtering scheme to improve readability, I would like to keep visible in the diagram also the states with 0 outcoming/incoming items (in this case minimum size but always greater than 0) and the same order (sorting is fine as is now).

**Comment by hski-github** [comment]
@f1li Could you share maybe a sample of the data and a screenshot of how it looks currently?

**Comment by f1li** [comment]
@hski-github I will prepare a small sample a d screens tomorrow. Thanks so much for now.

**Comment by f1li** [comment]
Hi @hski-github . Look at the attached screen. First one is the initial situation (no-filter). All the initial (left) and final (right) classes are present, A down-to H. Second screen instead is related to the same chart but after filtering operations. Few starting (and final) classes do not have any connections  and are then pruned out. In this way initial and final levels are no longer aligned. See Left D, corresponds visually with right C, Left G corresponds to right F. I would like to keep as much as possible the initial alignment adding spaces (blank)  and keeping in the viz also empty classes (although with minimal size). Hope I was clear enough. Thanks again.
![image](https://user-images.githubusercontent.com/74111096/119864260-c039cb00-bf1a-11eb-89b5-a0c9677dd26a.png)
![image](https://user-images.githubusercontent.com/74111096/119864304-caf46000-bf1a-11eb-97ab-24421e0f3d6d.png)

**Comment by hski-github** [comment]
I potentially could show empty categories like A, B, C on the left side with zero size. But does that help? 

But when data is filtered, inside the mod I don’t have information about what would be the values without filtering.

How about using marking instead of filtering? Elsewhere on the dashboard you would create possibility to mark the data you want to focus on. And then the non-marked data is greyed out in the Sankey.

**Comment by f1li** [comment]
I see your point Holger. Let me investigate the marking feature. However you are right, probably the best options would be to gray out the filtered data (leaving them in the chat for reference). Filtering would be better because (a) users don't have to change viz page (marking on the main page then moving to sankey to see the effect) (b) dashboard is consistent (I use filters placed on a sidebar everywhere in the dashboard).

Other than this issue I have another possible development to this mods. Feel free to create a new thread with this. My idea would be to show the transaction details once user clicks on the "rows". I have already prepared ironpython scripts to filter certain items. Then I only need to trigger a script when user click on the sankey row. Of course I will provide 1 script for each possible transaction (8 x 8). Thanks in advance.

**Comment by hski-github** [comment]
If you click on a row in Sankey, the respective row gets marked. You can create a detailed table visualisation for example, which is showing the marked data. See screenshot in the README or as a screenshot here https://raw.githubusercontent.com/hski-github/spotfire-sankey-diagram/main/examples/US%20Elections%20Sankey%20Diagram%20with%20Marking%20and%20Details.png

**Comment by f1li** [comment]
Yes, this was clear and already excellent feature. Unfortunately my case is a bit more complicated. Main table on which Sankey is evaluated is an aggregate PIVOT of a global detailed tables. Clicking on the sankey I would like to see exactly all the items which passed from a class to another one. If it was the classic electoral example, I would like to see all the single votes (i.e. persons) transitioning from  Obama to Trump. I have already the scripts to this, I just need the way to trigger them.

**Comment by hski-github** [comment]
Maybe you can create a relationship between the two tables Pivot and Raw and by that use the marking in Pivot to filter in Raw table.

**Comment by f1li** [comment]
It's going to be rather complicated for the current dashboard structure. Ideal implementation for my dashboard would see filtered values grayed out while unfiltered still highlighted.

**Comment by hski-github** [comment]
Don't know what to do here. Closing.
