### ISSUE TITLE
Bar tooltip not showing up

### ISSUE THREAD

**Issue by f1li** [hski-github/spotfire-sankey-diagram#20]
While in the previous version of the mods I was seeing also vertical bar tooltips, now I don't see them any longer. Did you decide to remove them? It was a useful feature to me.

**Comment by hski-github** [comment]
Thanks for reporting. I accidentally broke the vertical bar tooltips with some code change, but in the most recent source code it should be back. Could you please check out latest code and check again?

**Comment by hski-github** [comment]
Should be fixed since https://github.com/hski-github/spotfire-sankey-diagram/pull/11

**Comment by f1li** [comment]
OK. Let me download latest code and check. Will update here.

**Comment by f1li** [comment]
Holger, I downloaded latest code and tried to start the development server. Unfortunately I get the following error. Any clue?

![image](https://user-images.githubusercontent.com/74111096/122190433-1b177000-ce92-11eb-9167-15b5bf6015d3.png)

**Comment by hski-github** [comment]
Never done it in this way. README says, first call „npm install“ then „npm run server“

**Comment by f1li** [comment]
This is exactly what I did. If I move to the previous code dir it's fine (npm run server) and dev server starts correctly. When I jump in the new src dir I get the above issue.

**Comment by hski-github** [comment]
Please make sure to check out latest version of main branch. And maybe remove node_modules, then call „npm install“ then „npm run server“. This should work and I just checked, that it is working fine for me locally.

**Comment by hski-github** [comment]
I just check with the latest version of the code. Bar tool tip is shown. Hence closing this issue. Please feel free to reopen if it doesn't work for you with latest code.

**Comment by f1li** [comment]
I can confirm now this is fine. Thanks a lot. Final question on this: can you help me to change row tooltip count number format? Now I see real with 2 decimal digits but actually those are all integer...so I would like to see only 0 decimal digit. For bar tooltip instead this is already OK.

**Comment by hski-github** [comment]
See Open Topics in the README
