### ISSUE TITLE
Sankey on the TIBCO Community Exchange

### ISSUE THREAD

**Issue by arnaudspotfire** [hski-github/spotfire-sankey-diagram#7]
Hello,

I am Arnaud Varin, from the Spotfire product management team. I manage the publications of mods to the TIBCO Community Exchange. I tried your Sankey chart mod for Spotfire and it is great ! Congrats !

Would you be interested to share your mod with the Spotfire community on the [TIBCO Community Exchange](https://community.tibco.com/exchange/product/541/tags/spotfire-mods-43916)?
We have [this page](https://community.tibco.com/wiki/submitting-mods-tibco-community-exchange) where you will find all information on how to submit your mod for review.

Have a good day,
Arnaud

**Comment by hski-github** [comment]
Dear Arnaud,

thanks for getting in contact. Yes, would really like to submit the Sankey mod. I have to do some finalization like icon and tooltip and then will submit it. :-)

Best regards
Holger

**Comment by arnaudspotfire** [comment]
Excellent !

**Comment by hski-github** [comment]
End of April I submitted my request to publish Sankey on TIBCO Exchange. Legal and technical review process is ongoing. Yesterday submitted contributor agreement to TIBCO.

**Comment by f1li** [comment]
Oh I see Holger. Your mods is not yet officially in the TIBCO exchange. I am having trusting issue right now when I tried to deploy in PROD the sankey. In TEST everything was fine. In PROD the mods dos not have a trusted signature. I am struggling on this issue now.

**Comment by hski-github** [comment]
Available now https://community.tibco.com/exchange and https://community.tibco.com/modules/sankey-diagram-mod-tibco-spotfirer
